### ISSUE TITLE
Different keyboard shortcuts for different queries?

### ISSUE THREAD

**Issue by reagle** [rajeshvaya/sublime-online-searcher#1]
Great plugin! I'd like to use this to emulate WriteMonkey's lookup feature. It permits one to have different keyboard shortcuts for different queries. So for example alt+1 would be google, alt+2 would be php, etc. Any idea how that could be achieved?

**Comment by rajeshvaya** [comment]
Hello,

Thanks :) Currently there is not an easy way to do that (it is a nice feature to implement. I will add it soon), However you can ease out a litte by changing the key to search

e.g. to search on google you have to type in "google: jquery animate" but from the settings you can change it to "g: jquery animate"

There is also an ability to select default (no need to type in the key like google:) in the settings

I will let you know once i add the different shortcut to the release.

**Comment by reagle** [comment]
On 06/18/2014 01:23 AM, Rajesh Vaya wrote:

> e.g. to search on google you have to type in "google: jquery animate"
> but from the settings you can change it to "g: jquery animate"

Yes, I already did that, thank you!

> I will let you know once i add the different shortcut to the release.

Look forward to it :)
